export type NodeStatus = "required" | "recommended" | "milestone" | "start";
export type Difficulty = "Beginner" | "Intermediate" | "Advanced";

export interface RoadmapNode {
  id: string;
  label: string;
  slug?: string;
  subject?: string;
  difficulty: Difficulty;
  duration?: string;
  status: NodeStatus;
  description?: string;
}

export interface RoadmapEdge {
  id: string;
  source: string;
  target: string;
  type?: "required" | "recommended";
}

export interface Roadmap {
  slug: string;
  title: string;
  description: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  topicCount: number;
  duration: string;
  nodes: RoadmapNode[];
  edges: RoadmapEdge[];
}

export const roadmaps: Roadmap[] = [
  {
    slug: "ml-engineer",
    title: "ML Engineer",
    description: "Master supervised learning, loss optimization, regularization, and model evaluation from mathematical roots to production code.",
    level: "Intermediate",
    topicCount: 15,
    duration: "8 weeks",
    nodes: [
      { id: "python", label: "Python Fundamentals", difficulty: "Beginner", duration: "1 week", status: "start", description: "Core Python, NumPy, Pandas basics" },
      { id: "math", label: "Math for ML", difficulty: "Beginner", duration: "2 weeks", status: "required", slug: "linear-algebra", subject: "mathematics", description: "Linear algebra, calculus, probability" },
      { id: "stats", label: "Statistics", difficulty: "Beginner", duration: "1 week", status: "required", slug: "probability-distributions", subject: "mathematics", description: "Distributions, hypothesis testing, MLE" },
      { id: "linear-algebra", label: "Linear Algebra", difficulty: "Beginner", duration: "1 week", status: "required", slug: "linear-algebra", subject: "mathematics", description: "Vectors, matrices, eigenvalues, SVD" },
      { id: "ml-fundamentals", label: "ML Fundamentals", difficulty: "Intermediate", duration: "1 week", status: "required", description: "Bias-variance, overfitting, cross-validation" },
      { id: "regression", label: "Regression", difficulty: "Beginner", slug: "simple-linear-regression", subject: "machine-learning", duration: "1 week", status: "required", description: "Linear, multiple, polynomial regression" },
      { id: "classification", label: "Classification", difficulty: "Intermediate", slug: "classification-fundamentals", subject: "machine-learning", duration: "1 week", status: "required", description: "Logistic regression, SVM, k-NN" },
      { id: "trees", label: "Trees & Ensembles", difficulty: "Intermediate", slug: "decision-tree-fundamentals", subject: "machine-learning", duration: "2 weeks", status: "required", description: "Decision trees, random forests, gradient boosting" },
      { id: "clustering", label: "Clustering", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "K-means, DBSCAN, hierarchical clustering" },
      { id: "feature-eng", label: "Feature Engineering", difficulty: "Intermediate", duration: "1 week", status: "required", description: "Scaling, encoding, feature selection" },
      { id: "model-eval", label: "Model Evaluation", difficulty: "Intermediate", slug: "regression-evaluation", subject: "machine-learning", duration: "1 week", status: "required", description: "Metrics, confusion matrix, ROC-AUC" },
      { id: "dl-basics", label: "Deep Learning Basics", difficulty: "Intermediate", slug: "neural-network-fundamentals", subject: "deep-learning", duration: "2 weeks", status: "recommended", description: "Neural networks, backpropagation, PyTorch" },
      { id: "mlops", label: "MLOps Basics", difficulty: "Intermediate", slug: "experiment-tracking", subject: "mlops", duration: "1 week", status: "recommended", description: "Model serving, monitoring, CI/CD" },
      { id: "capstone", label: "Capstone Project", difficulty: "Advanced", duration: "2 weeks", status: "milestone", description: "End-to-end ML pipeline with real data" },
    ],
    edges: [
      { id: "e1", source: "python", target: "math", type: "required" },
      { id: "e2", source: "python", target: "linear-algebra", type: "required" },
      { id: "e3", source: "math", target: "stats", type: "required" },
      { id: "e4", source: "math", target: "ml-fundamentals", type: "required" },
      { id: "e5", source: "linear-algebra", target: "ml-fundamentals", type: "required" },
      { id: "e6", source: "stats", target: "ml-fundamentals", type: "required" },
      { id: "e7", source: "ml-fundamentals", target: "regression", type: "required" },
      { id: "e8", source: "ml-fundamentals", target: "classification", type: "required" },
      { id: "e9", source: "ml-fundamentals", target: "clustering", type: "recommended" },
      { id: "e10", source: "regression", target: "trees", type: "required" },
      { id: "e11", source: "classification", target: "trees", type: "required" },
      { id: "e12", source: "regression", target: "feature-eng", type: "required" },
      { id: "e13", source: "classification", target: "feature-eng", type: "required" },
      { id: "e14", source: "trees", target: "model-eval", type: "required" },
      { id: "e15", source: "feature-eng", target: "model-eval", type: "required" },
      { id: "e16", source: "model-eval", target: "dl-basics", type: "recommended" },
      { id: "e17", source: "model-eval", target: "mlops", type: "recommended" },
      { id: "e18", source: "dl-basics", target: "capstone", type: "required" },
      { id: "e19", source: "mlops", target: "capstone", type: "recommended" },
    ],
  },
  {
    slug: "deep-learning-engineer",
    title: "Deep Learning Engineer",
    description: "Build deep neural networks, CNNs, RNNs, and transformer architectures from scratch to production.",
    level: "Advanced",
    topicCount: 14,
    duration: "10 weeks",
    nodes: [
      { id: "python-dl", label: "Python & NumPy", difficulty: "Beginner", duration: "1 week", status: "start", description: "Python proficiency and NumPy array operations" },
      { id: "math-dl", label: "Math Foundations", difficulty: "Beginner", duration: "2 weeks", status: "required", description: "Linear algebra, calculus, probability" },
      { id: "nn-fundamentals", label: "Neural Network Fundamentals", difficulty: "Intermediate", slug: "loss-function-and-gradient-descent", duration: "2 weeks", status: "required", description: "Forward pass, backpropagation, loss functions" },
      { id: "optimization", label: "Optimization", difficulty: "Intermediate", duration: "1 week", status: "required", description: "SGD, Adam, learning rate schedules" },
      { id: "cnn", label: "CNNs", difficulty: "Intermediate", duration: "2 weeks", status: "required", description: "Convolutional networks, transfer learning" },
      { id: "rnn", label: "RNNs & LSTMs", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "Recurrent networks, sequence modeling" },
      { id: "attention", label: "Attention Mechanisms", difficulty: "Advanced", duration: "1 week", status: "required", description: "Self-attention, multi-head attention" },
      { id: "transformers", label: "Transformers", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "Encoder-decoder, positional encoding, BERT, GPT" },
      { id: "generation", label: "Generative Models", difficulty: "Advanced", duration: "2 weeks", status: "recommended", description: "GANs, VAEs, diffusion models" },
      { id: "training", label: "Training at Scale", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "Mixed precision, distributed training, gradient accumulation" },
      { id: "deployment", label: "Model Deployment", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "ONNX, TensorRT, quantization" },
      { id: "capstone-dl", label: "Capstone Project", difficulty: "Advanced", duration: "3 weeks", status: "milestone", description: "Build and deploy a transformer model end-to-end" },
    ],
    edges: [
      { id: "de1", source: "python-dl", target: "math-dl", type: "required" },
      { id: "de2", source: "math-dl", target: "nn-fundamentals", type: "required" },
      { id: "de3", source: "nn-fundamentals", target: "optimization", type: "required" },
      { id: "de4", source: "optimization", target: "cnn", type: "required" },
      { id: "de5", source: "optimization", target: "rnn", type: "recommended" },
      { id: "de6", source: "cnn", target: "attention", type: "required" },
      { id: "de7", source: "rnn", target: "attention", type: "recommended" },
      { id: "de8", source: "attention", target: "transformers", type: "required" },
      { id: "de9", source: "transformers", target: "generation", type: "recommended" },
      { id: "de10", source: "transformers", target: "training", type: "recommended" },
      { id: "de11", source: "training", target: "deployment", type: "recommended" },
      { id: "de12", source: "transformers", target: "capstone-dl", type: "required" },
      { id: "de13", source: "deployment", target: "capstone-dl", type: "recommended" },
    ],
  },
  {
    slug: "llm-engineer",
    title: "LLM Engineer",
    description: "Master large language models — from transformer internals to fine-tuning, RAG, and building AI agents.",
    level: "Advanced",
    topicCount: 16,
    duration: "12 weeks",
    nodes: [
      { id: "python-llm", label: "Python & PyTorch", difficulty: "Beginner", duration: "1 week", status: "start", description: "Python, PyTorch tensors, autograd" },
      { id: "nn-llm", label: "Neural Networks", difficulty: "Intermediate", duration: "2 weeks", status: "required", description: "Feedforward, backprop, regularization" },
      { id: "attention-llm", label: "Self-Attention", difficulty: "Intermediate", duration: "1 week", status: "required", description: "Scaled dot-product attention, masking" },
      { id: "transformer-llm", label: "Transformers", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "Encoder, decoder, positional encoding" },
      { id: "pretraining", label: "Pre-training", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "Language modeling, next-token prediction" },
      { id: "tokenization", label: "Tokenization", difficulty: "Intermediate", duration: "1 week", status: "required", slug: "tokenization", description: "BPE, WordPiece, SentencePiece" },
      { id: "fine-tuning", label: "Fine-tuning", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "SFT, LoRA, QLoRA, DPO" },
      { id: "rag", label: "RAG", difficulty: "Advanced", duration: "1 week", status: "required", description: "Retrieval-augmented generation, vector stores" },
      { id: "eval", label: "LLM Evaluation", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "BLEU, ROUGE, human eval, benchmarks" },
      { id: "prompt-eng", label: "Prompt Engineering", difficulty: "Beginner", duration: "1 week", status: "recommended", description: "Few-shot, chain-of-thought, system prompts" },
      { id: "agents", label: "AI Agents", difficulty: "Advanced", duration: "2 weeks", status: "recommended", description: "Tool use, planning, multi-agent systems" },
      { id: "safety", label: "AI Safety & Alignment", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "RLHF, constitutional AI, red-teaming" },
      { id: "serving", label: "LLM Serving", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "vLLM, TGI, quantization, batching" },
      { id: "capstone-llm", label: "Capstone Project", difficulty: "Advanced", duration: "3 weeks", status: "milestone", description: "Build a fine-tuned LLM with RAG pipeline" },
    ],
    edges: [
      { id: "le1", source: "python-llm", target: "nn-llm", type: "required" },
      { id: "le2", source: "nn-llm", target: "attention-llm", type: "required" },
      { id: "le3", source: "attention-llm", target: "transformer-llm", type: "required" },
      { id: "le4", source: "transformer-llm", target: "pretraining", type: "required" },
      { id: "le5", source: "transformer-llm", target: "tokenization", type: "required" },
      { id: "le6", source: "pretraining", target: "fine-tuning", type: "required" },
      { id: "le7", source: "tokenization", target: "fine-tuning", type: "required" },
      { id: "le8", source: "fine-tuning", target: "rag", type: "required" },
      { id: "le9", source: "fine-tuning", target: "eval", type: "recommended" },
      { id: "le10", source: "transformer-llm", target: "prompt-eng", type: "recommended" },
      { id: "le11", source: "rag", target: "agents", type: "recommended" },
      { id: "le12", source: "fine-tuning", target: "safety", type: "recommended" },
      { id: "le13", source: "pretraining", target: "serving", type: "recommended" },
      { id: "le14", source: "rag", target: "capstone-llm", type: "required" },
      { id: "le15", source: "agents", target: "capstone-llm", type: "recommended" },
    ],
  },
  {
    slug: "ai-researcher",
    title: "AI Researcher",
    description: "From mathematical foundations to reproducing papers and conducting original research in AI/ML.",
    level: "Advanced",
    topicCount: 14,
    duration: "14 weeks",
    nodes: [
      { id: "math-r", label: "Advanced Mathematics", difficulty: "Beginner", duration: "3 weeks", status: "start", description: "Linear algebra, real analysis, probability theory" },
      { id: "ml-theory", label: "ML Theory", difficulty: "Intermediate", duration: "2 weeks", status: "required", description: "PAC learning, VC dimension, generalization bounds" },
      { id: "prob-ml", label: "Probabilistic ML", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "Bayesian inference, graphical models, variational methods" },
      { id: "optimization-r", label: "Optimization Theory", difficulty: "Advanced", duration: "1 week", status: "required", description: "Convex optimization, duality, KKT conditions" },
      { id: "dl-theory", label: "Deep Learning Theory", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "Neural tangent kernels, implicit regularization" },
      { id: "paper-reading", label: "Paper Reading", difficulty: "Intermediate", duration: "1 week", status: "required", description: "How to read and critique ML papers" },
      { id: "reproduction", label: "Paper Reproduction", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "Reproduce results from key papers" },
      { id: "experimental-design", label: "Experimental Design", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "Ablation studies, statistical significance" },
      { id: "writing", label: "Research Writing", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "Writing papers, LaTeX, scientific communication" },
      { id: "前沿", label: "Current Research", difficulty: "Advanced", duration: "ongoing", status: "required", description: "Follow arXiv, attend seminars, read recent work" },
      { id: "capstone-r", label: "Original Research", difficulty: "Advanced", duration: "4 weeks", status: "milestone", description: "Conduct and write up original research" },
    ],
    edges: [
      { id: "re1", source: "math-r", target: "ml-theory", type: "required" },
      { id: "re2", source: "math-r", target: "prob-ml", type: "required" },
      { id: "re3", source: "ml-theory", target: "optimization-r", type: "required" },
      { id: "re4", source: "prob-ml", target: "dl-theory", type: "required" },
      { id: "re5", source: "optimization-r", target: "dl-theory", type: "required" },
      { id: "re6", source: "dl-theory", target: "paper-reading", type: "required" },
      { id: "re7", source: "paper-reading", target: "reproduction", type: "required" },
      { id: "re8", source: "paper-reading", target: "experimental-design", type: "recommended" },
      { id: "re9", source: "paper-reading", target: "writing", type: "recommended" },
      { id: "re10", source: "reproduction", target: "前沿", type: "required" },
      { id: "re11", source: "reproduction", target: "capstone-r", type: "required" },
      { id: "re12", source: "experimental-design", target: "capstone-r", type: "recommended" },
      { id: "re13", source: "writing", target: "capstone-r", type: "recommended" },
    ],
  },
  {
    slug: "computer-vision",
    title: "Computer Vision Engineer",
    description: "Master image classification, object detection, segmentation, and multimodal AI systems.",
    level: "Advanced",
    topicCount: 14,
    duration: "10 weeks",
    nodes: [
      { id: "python-cv", label: "Python & OpenCV", difficulty: "Beginner", duration: "1 week", status: "start", description: "Image processing basics, OpenCV operations" },
      { id: "nn-cv", label: "Neural Networks", difficulty: "Intermediate", duration: "2 weeks", status: "required", description: "Feedforward networks, backpropagation" },
      { id: "cnn-cv", label: "CNNs", difficulty: "Intermediate", duration: "2 weeks", status: "required", description: "Conv layers, pooling, architectures" },
      { id: "classification-cv", label: "Image Classification", difficulty: "Intermediate", duration: "1 week", status: "required", description: "Transfer learning, fine-tuning pretrained models" },
      { id: "detection", label: "Object Detection", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "YOLO, R-CNN, anchor-based methods" },
      { id: "segmentation-cv", label: "Segmentation", difficulty: "Advanced", duration: "1 week", status: "required", description: "U-Net, Mask R-CNN, semantic/instance segmentation" },
      { id: "vit", label: "Vision Transformers", difficulty: "Advanced", duration: "1 week", status: "required", description: "ViT, DeiT, Swin Transformer" },
      { id: "multimodal", label: "Multimodal AI", difficulty: "Advanced", duration: "2 weeks", status: "recommended", description: "CLIP, LLaVA, vision-language models" },
      { id: "3d-vision", label: "3D Vision", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "Point clouds, NeRF, depth estimation" },
      { id: "video", label: "Video Understanding", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "Action recognition, video transformers" },
      { id: "deployment-cv", label: "Edge Deployment", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "ONNX, TensorRT, model optimization" },
      { id: "capstone-cv", label: "Capstone Project", difficulty: "Advanced", duration: "3 weeks", status: "milestone", description: "Build a full CV pipeline with detection + segmentation" },
    ],
    edges: [
      { id: "ce1", source: "python-cv", target: "nn-cv", type: "required" },
      { id: "ce2", source: "nn-cv", target: "cnn-cv", type: "required" },
      { id: "ce3", source: "cnn-cv", target: "classification-cv", type: "required" },
      { id: "ce4", source: "classification-cv", target: "detection", type: "required" },
      { id: "ce5", source: "classification-cv", target: "segmentation-cv", type: "required" },
      { id: "ce6", source: "detection", target: "vit", type: "required" },
      { id: "ce7", source: "segmentation-cv", target: "vit", type: "required" },
      { id: "ce8", source: "vit", target: "multimodal", type: "recommended" },
      { id: "ce9", source: "vit", target: "3d-vision", type: "recommended" },
      { id: "ce10", source: "vit", target: "video", type: "recommended" },
      { id: "ce11", source: "classification-cv", target: "deployment-cv", type: "recommended" },
      { id: "ce12", source: "detection", target: "capstone-cv", type: "required" },
      { id: "ce13", source: "segmentation-cv", target: "capstone-cv", type: "required" },
    ],
  },
  {
    slug: "mlops",
    title: "MLOps Engineer",
    description: "Bridge the gap between model prototyping and production — CI/CD, monitoring, feature stores, and deployment.",
    level: "Intermediate",
    topicCount: 13,
    duration: "8 weeks",
    nodes: [
      { id: "python-mlops", label: "Python & CLI", difficulty: "Beginner", duration: "1 week", status: "start", description: "Python scripting, shell, git basics" },
      { id: "ml-basics-mlops", label: "ML Basics", difficulty: "Intermediate", duration: "2 weeks", status: "required", description: "Model training, evaluation, common algorithms" },
      { id: "data-eng", label: "Data Engineering", difficulty: "Intermediate", duration: "1 week", status: "required", description: "ETL pipelines, data validation, schema enforcement" },
      { id: "feature-stores", label: "Feature Stores", difficulty: "Intermediate", duration: "1 week", status: "required", description: "Feature engineering, versioning, serving" },
      { id: "experiment-tracking", label: "Experiment Tracking", difficulty: "Intermediate", duration: "1 week", status: "required", description: "MLflow, W&B, hyperparameter management" },
      { id: "model-registry", label: "Model Registry", difficulty: "Intermediate", duration: "1 week", status: "required", description: "Model versioning, staging, approval workflows" },
      { id: "containerization", label: "Docker & Containers", difficulty: "Intermediate", duration: "1 week", status: "required", slug: "containerization", description: "Docker, Kubernetes basics, container orchestration" },
      { id: "serving", label: "Model Serving", difficulty: "Intermediate", duration: "1 week", status: "required", description: "FastAPI, BentoML, real-time vs batch serving" },
      { id: "monitoring", label: "Monitoring & Drift", difficulty: "Intermediate", duration: "1 week", status: "required", description: "Data drift, model performance monitoring, alerts" },
      { id: "cicd", label: "CI/CD for ML", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "GitHub Actions, automated testing, deployment" },
      { id: "cloud", label: "Cloud ML Services", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "AWS SageMaker, GCP Vertex AI, Azure ML" },
      { id: "capstone-mlops", label: "Capstone Project", difficulty: "Advanced", duration: "2 weeks", status: "milestone", description: "End-to-end ML pipeline with monitoring and CI/CD" },
    ],
    edges: [
      { id: "me1", source: "python-mlops", target: "ml-basics-mlops", type: "required" },
      { id: "me2", source: "ml-basics-mlops", target: "data-eng", type: "required" },
      { id: "me3", source: "data-eng", target: "feature-stores", type: "required" },
      { id: "me4", source: "ml-basics-mlops", target: "experiment-tracking", type: "required" },
      { id: "me5", source: "experiment-tracking", target: "model-registry", type: "required" },
      { id: "me6", source: "feature-stores", target: "containerization", type: "required" },
      { id: "me7", source: "model-registry", target: "containerization", type: "required" },
      { id: "me8", source: "containerization", target: "serving", type: "required" },
      { id: "me9", source: "serving", target: "monitoring", type: "required" },
      { id: "me10", source: "serving", target: "cicd", type: "recommended" },
      { id: "me11", source: "containerization", target: "cloud", type: "recommended" },
      { id: "me12", source: "monitoring", target: "capstone-mlops", type: "required" },
      { id: "me13", source: "cicd", target: "capstone-mlops", type: "recommended" },
    ],
  },
  {
    slug: "nlp-engineer",
    title: "NLP Engineer",
    description: "Build language models, text classifiers, named entity recognizers, and conversational AI systems.",
    level: "Intermediate",
    topicCount: 13,
    duration: "10 weeks",
    nodes: [
      { id: "python-nlp", label: "Python & NLTK", difficulty: "Beginner", duration: "1 week", status: "start", description: "Text processing, tokenization, regex" },
      { id: "linguistics", label: "Linguistics Basics", difficulty: "Beginner", duration: "1 week", status: "required", description: "Morphology, syntax, semantics overview" },
      { id: "text-repr", label: "Text Representations", difficulty: "Intermediate", duration: "1 week", status: "required", slug: "tokenization", description: "Bag of words, TF-IDF, word embeddings" },
      { id: "word2vec", label: "Word Embeddings", difficulty: "Intermediate", duration: "1 week", status: "required", description: "Word2Vec, GloVe, FastText" },
      { id: "seq-models", label: "Sequence Models", difficulty: "Intermediate", duration: "2 weeks", status: "required", description: "RNNs, LSTMs, GRUs for text" },
      { id: "attention-nlp", label: "Attention Mechanisms", difficulty: "Advanced", duration: "1 week", status: "required", slug: "self-attention", description: "Self-attention, cross-attention" },
      { id: "bert", label: "BERT & Encoders", difficulty: "Advanced", duration: "1 week", status: "required", slug: "bert-architecture", description: "BERT, RoBERTa, encoder fine-tuning" },
      { id: "gpt", label: "GPT & Decoders", difficulty: "Advanced", duration: "1 week", status: "required", description: "GPT architecture, autoregressive generation" },
      { id: "ner", label: "NER & Parsing", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "Named entity recognition, dependency parsing" },
      { id: "summarization", label: "Summarization & QA", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "Abstractive/extractive summarization, question answering" },
      { id: "deployment-nlp", label: "NLP Deployment", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "Model optimization, API serving, edge deployment" },
      { id: "capstone-nlp", label: "Capstone Project", difficulty: "Advanced", duration: "2 weeks", status: "milestone", description: "Build a complete NLP pipeline with fine-tuned BERT" },
    ],
    edges: [
      { id: "ne1", source: "python-nlp", target: "linguistics", type: "required" },
      { id: "ne2", source: "linguistics", target: "text-repr", type: "required" },
      { id: "ne3", source: "text-repr", target: "word2vec", type: "required" },
      { id: "ne4", source: "word2vec", target: "seq-models", type: "required" },
      { id: "ne5", source: "seq-models", target: "attention-nlp", type: "required" },
      { id: "ne6", source: "attention-nlp", target: "bert", type: "required" },
      { id: "ne7", source: "attention-nlp", target: "gpt", type: "required" },
      { id: "ne8", source: "seq-models", target: "ner", type: "recommended" },
      { id: "ne9", source: "bert", target: "summarization", type: "recommended" },
      { id: "ne10", source: "bert", target: "deployment-nlp", type: "recommended" },
      { id: "ne11", source: "bert", target: "capstone-nlp", type: "required" },
      { id: "ne12", source: "gpt", target: "capstone-nlp", type: "required" },
    ],
  },
  {
    slug: "ai-agent-engineer",
    title: "AI Agent Engineer",
    description: "Build autonomous AI agents that can reason, plan, use tools, and interact with the real world.",
    level: "Advanced",
    topicCount: 12,
    duration: "10 weeks",
    nodes: [
      { id: "python-ag", label: "Python & APIs", difficulty: "Beginner", duration: "1 week", status: "start", description: "Python, HTTP, async programming" },
      { id: "llm-basics", label: "LLM Fundamentals", difficulty: "Intermediate", duration: "2 weeks", status: "required", description: "Transformers, inference, API usage" },
      { id: "prompt-ag", label: "Prompt Engineering", difficulty: "Intermediate", duration: "1 week", status: "required", description: "System prompts, few-shot, CoT" },
      { id: "tool-use", label: "Tool Use", difficulty: "Advanced", duration: "1 week", status: "required", description: "Function calling, API integration" },
      { id: "planning", label: "Planning & Reasoning", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "ReAct, chain-of-thought, task decomposition" },
      { id: "memory", label: "Memory Systems", difficulty: "Advanced", duration: "1 week", status: "required", description: "Short/long-term memory, vector stores" },
      { id: "multi-agent", label: "Multi-Agent Systems", difficulty: "Advanced", duration: "2 weeks", status: "recommended", description: "Agent orchestration, communication protocols" },
      { id: "rag-ag", label: "RAG for Agents", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "Retrieval-augmented generation for agent context" },
      { id: "eval-ag", label: "Agent Evaluation", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "Benchmarks, testing, human evaluation" },
      { id: "safety-ag", label: "Safety & Guardrails", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "Input validation, output filtering, sandboxing" },
      { id: "capstone-ag", label: "Capstone Project", difficulty: "Advanced", duration: "3 weeks", status: "milestone", description: "Build a multi-tool autonomous agent" },
    ],
    edges: [
      { id: "ae1", source: "python-ag", target: "llm-basics", type: "required" },
      { id: "ae2", source: "llm-basics", target: "prompt-ag", type: "required" },
      { id: "ae3", source: "prompt-ag", target: "tool-use", type: "required" },
      { id: "ae4", source: "tool-use", target: "planning", type: "required" },
      { id: "ae5", source: "planning", target: "memory", type: "required" },
      { id: "ae6", source: "memory", target: "multi-agent", type: "recommended" },
      { id: "ae7", source: "memory", target: "rag-ag", type: "recommended" },
      { id: "ae8", source: "planning", target: "eval-ag", type: "recommended" },
      { id: "ae9", source: "tool-use", target: "safety-ag", type: "recommended" },
      { id: "ae10", source: "memory", target: "capstone-ag", type: "required" },
      { id: "ae11", source: "planning", target: "capstone-ag", type: "required" },
    ],
  },
  {
    slug: "generative-ai",
    title: "Generative AI Engineer",
    description: "Build with diffusion models, GANs, VAEs, and modern generative systems for images, text, and beyond.",
    level: "Advanced",
    topicCount: 12,
    duration: "10 weeks",
    nodes: [
      { id: "python-gen", label: "Python & PyTorch", difficulty: "Beginner", duration: "1 week", status: "start", description: "PyTorch, tensor operations, autograd" },
      { id: "nn-gen", label: "Neural Networks", difficulty: "Intermediate", duration: "2 weeks", status: "required", description: "Feedforward, CNNs, backpropagation" },
      { id: "vae", label: "VAEs", difficulty: "Advanced", duration: "1 week", status: "required", description: "Variational autoencoders, latent spaces" },
      { id: "gan", label: "GANs", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "Generative adversarial networks, training dynamics" },
      { id: "diffusion", label: "Diffusion Models", difficulty: "Advanced", duration: "2 weeks", status: "required", description: "DDPM, score matching, guided generation" },
      { id: "text-gen", label: "Text Generation", difficulty: "Advanced", duration: "1 week", status: "required", description: "Autoregressive models, sampling strategies" },
      { id: "multimodal-gen", label: "Multimodal Generation", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "Image-to-text, text-to-image, CLIP" },
      { id: "control", label: "Controlled Generation", difficulty: "Advanced", duration: "1 week", status: "recommended", description: "ControlNet, LoRA, style transfer" },
      { id: "eval-gen", label: "Evaluation Metrics", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "FID, IS, human evaluation" },
      { id: "deployment-gen", label: "Deployment", difficulty: "Intermediate", duration: "1 week", status: "recommended", description: "Model optimization, API serving" },
      { id: "capstone-gen", label: "Capstone Project", difficulty: "Advanced", duration: "3 weeks", status: "milestone", description: "Build a text-to-image pipeline with diffusion models" },
    ],
    edges: [
      { id: "ge1", source: "python-gen", target: "nn-gen", type: "required" },
      { id: "ge2", source: "nn-gen", target: "vae", type: "required" },
      { id: "ge3", source: "nn-gen", target: "gan", type: "required" },
      { id: "ge4", source: "vae", target: "diffusion", type: "required" },
      { id: "ge5", source: "gan", target: "diffusion", type: "required" },
      { id: "ge6", source: "nn-gen", target: "text-gen", type: "required" },
      { id: "ge7", source: "diffusion", target: "multimodal-gen", type: "recommended" },
      { id: "ge8", source: "diffusion", target: "control", type: "recommended" },
      { id: "ge9", source: "diffusion", target: "eval-gen", type: "recommended" },
      { id: "ge10", source: "nn-gen", target: "deployment-gen", type: "recommended" },
      { id: "ge11", source: "diffusion", target: "capstone-gen", type: "required" },
    ],
  },
];

export function getRoadmapBySlug(slug: string): Roadmap | undefined {
  return roadmaps.find((r) => r.slug === slug);
}
